
version: "3.9"

services:
  backend:
    build:
      context: ../backend
    container_name: clinia-backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ../frontend
    container_name: clinia-frontend
    ports:
      - "5173:5173"
    env_file:
      - ../.env
    volumes:
      - ../frontend:/app
    command: npm run dev
